//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by zhaoliang.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW_ADD                101
#define ID_INDICATOR_LOGIN              101
#define IDR_MAINFRAME                   128
#define IDR_PERSONTYPE                  129
#define IDB_PEOPLE                      139
#define IDD_DLG_LOGIN                   140
#define IDD_FORMVIEW_CHANGE             141
#define IDD_FORMVIEW_SEARCH             142
#define IDC_STATIC_LOGINTEXT            1000
#define IDC_CMD_DSN                     1001
#define IDC_EDT_USER                    1002
#define IDC_EDT_PASSWD                  1003
#define IDC_ADD_EDT_ID                  1003
#define IDC_ADD_EDT_PASSWD              1004
#define IDC_ADD_EDT_NAME                1005
#define IDC_ADD_RADIO_MALE              1006
#define IDC_ADD_RADIO_FEMALE            1007
#define IDC_ADD_EDT_BIRTHDAY            1008
#define IDC_ADD_CMB_DEPARTMENT          1009
#define IDC_ADD_CMB_JOB                 1010
#define IDC_ADD_CMB_EDULEVEL            1011
#define IDC_ADD_EDT_SPECIALTY           1012
#define IDC_ADD_EDT_ADDRESS             1013
#define IDC_ADD_EDT_TEL                 1014
#define IDC_ADD_EDT_EMAIL               1015
#define IDC_ADD_EDT_MEMO                1016
#define IDC_ADD_BTN_ADD                 1017
#define IDC_CHANGE_EDT_ID               1018
#define IDC_CHANGE_RADIO_JOB            1019
#define IDC_CHANGE_RADIO_FIRE           1020
#define IDC_CHANGE_DATETIMEPICKER       1021
#define IDC_CHANGE_EDT_NAME             1022
#define IDC_CHANGE_CMB_DEPARTMENT       1023
#define IDC_CHANGE_CMB_JOB              1024
#define IDC_CHANGE_EDT_DESCRIPTION      1025
#define IDC_CHANGE_BTN_CHANGE           1026
#define IDC_SEARCH_EDT_PASSWD           1028
#define IDC_SEARCH_RADIO_MALE           1029
#define IDC_SEARCH_RADIO_FEMALE         1030
#define IDC_SEARCH_EDT_BIRTHDAY         1031
#define IDC_SEARCH_EDT_ADDRESS          1032
#define IDC_SEARCH_EDT_TEL              1033
#define IDC_SEARCH_EDT_EMAIL            1034
#define IDC_SEARCH_EDT_MEMO             1035
#define IDC_SEARCH_EDT_SPECIALTY        1036
#define IDC_SEARCH_CMB_EDULEVEL         1037
#define IDC_SEARCH_BTN_CHGPASSWD        1038
#define IDC_CHANGE_LIST                 1039
#define IDC_SEARCH_LIST                 1039
#define IDC_SEARCH_EDT_ID               1040
#define IDC_SEARCH_CMB_DEPARTMENT       1041
#define IDC_SEARCH_CMB_JOB              1042
#define IDC_SEARCH_EDT_NAME             1043
#define IDC_SEARCH_BTN_CHANGE           1044
#define IDM_SYSTEM_CONNECT              32771
#define ID_SYSTEM_CONNECT               32771
#define IDM_MANAGE_ADD                  32772
#define ID_MANAGE_ADD                   32772
#define IDM_WINDOW_CASCADE              32773
#define IDM_SYSTEM_DISCONNECT           32774
#define ID_SYSTEM_DISCONNECT            32774
#define IDM_SYSTEM_EXIT                 32775
#define ID_SYSTEM_EXIT                  32775
#define IDM_MANAGER_CHANGE              32776
#define ID_MANAGER_CHANGE               32776
#define IDM_MANAGER_SEARCH              32777
#define ID_MANAGER_SEARCH               32777
#define IDM_WINDOW_TILE_H               32778
#define ID_WINDOW_TILE_H                32778
#define IDM_WINDOW_TILE_V               32779
#define ID_WINDOW_TILE_V                32779
#define IDM_WINDOW_MINIALL              32780
#define ID_WINDOW_MINIALL               32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
